### ISSUE TITLE
"No Internet Connection Found" overlay is transparent and interferes with other elements

### ISSUE THREAD

**Issue by woodser** [mymonero/mymonero-app-js#106]
1. Disconnect from internet
2. Open app
3. Import wallet
4. "No Internet Connection Found" overlay is transparent so text is unreadable over other elements.  Cannot access '?' description for mnemonic seed

**Comment by paulshapiro** [comment]
Showing an "offline" banner was the intended functionality (ala Slack) – because, at least at the moment, much of the functionality and info in the app is not usable or kept updated without an internet connection – but it was not the intended user experience. Thanks for reporting. I'll make the overlay opaque instead and pick a more suitable font color.

**Comment by paulshapiro** [comment]
Closed by https://github.com/mymonero/mymonero-app-js/commit/b87291d47db6272fb24ad20771626288062d5519
