### ISSUE TITLE
Broken for Tor browser

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [mymonero/mymonero-app-js#158]
First, thanks for this awesomely simple online wallet!

It would be nice to be able to use the website with the tor browser.
It seems to have issues rendering content. Is this due to Angular not supporting the browser?

As you can see, it is just empty:

<img width="994" alt="screen shot 2017-12-20 at 17 11 23" src="https://user-images.githubusercontent.com/12467511/34216607-16d871f4-e5a9-11e7-9bb8-2fc26a9d0821.png">

Browser: Tor Browser v. 7.0.11 (based on Mozilla Firefox 52.5.2)
(which is the latest Tor Browser version)
Browser Settings: Javascript Enabled, Security Level: Low
OS: MacOS 10.13.1

I’ve seen that there is an open issue regarding Tor network #85  but I think it’s not related, since this issue is now about implementing the Tor network and some .onion domain, but about fixing the existing site for that browser.

IDK if there are any plans by Onion to use a newer browser version

**Comment by DiMiTri101** [comment]
Don't use mymonero.com over tor. You will get MITM'd.

**Comment by ThibaultJanBeyer** [comment]
Should still be accessible tho’
One could add a message like "browsing mymonero.com is not secure, even if you use Tor. We are working on an alternative especially for Tor." and the options "I understand but want to continue at my own risk"…
Blocking the browser completely does not make any sense in my opinion.

**Comment by paulshapiro** [comment]
Closing this, because this is the repo for mymonero-app-js, not the current mymonero.com web wallet. In response, I will be adding an attestation or requirements to submitting issues on this repository where you affirm it's not about the old mymonero.com web wallet. Blocking the browser actually does make sense because we're not in the business of representing the wallet is safe to our knowledge when there is the obvious risk of MITM over Tor. Thanks for the feature idea however and I hope you continue to give us feedback on our new apps in the future.

**Comment by ThibaultJanBeyer** [comment]
Yeah, just noticed that this is not the `mymonero.com` after having built the project locally. Sorry about that. Is a bit confusing. I still don’t agree about blocking browsers. There are various possibilities for MITM, even if it’s not over Tor. A man in the middle attack can easily be done, no matter which browser one uses. But I accept your decision. Thanks for taking the time to review this issue.

**Comment by paulshapiro** [comment]
Please feel free then to create additional issues here detailing other such possible vulnerabilities which you may have discovered, and we will have our experts look at it. We think very highly of contributions. However just because there are vulnerabilities doesn't mean we should increase them. Thanks again.

**Comment by DiMiTri101** [comment]
Tor just isn't safe in general
