### ISSUE TITLE
Error in UnspentOuts function???

### ISSUE THREAD

**Issue by SergeyAnkarenko** [mymonero/mymonero-app-js#166]
My balance is 
![image](https://user-images.githubusercontent.com/6827668/37567386-4329a5f2-2ad7-11e8-8437-94ad62df16d4.png)

When debugging ```hostedMoneroAPIClient.UnspentOuts``` function returns one unused output ...
![image](https://user-images.githubusercontent.com/6827668/37567373-21a83060-2ad7-11e8-8e0a-8c73840f5e59.png)

I guess, summary of unspent amounts should be equal to balance, which is not true in this particular case.
Is it bug? I don't understand

**Comment by paulshapiro** [comment]
Hi @SergeyAnkarenko,

It's possible that you've found one of the rare cases where you loaded unspent outs while the server was processing a reorg, or there's a small chance you may have encountered a mempool scanning condition in which for example new funds are coming in or going out. (I'm assuming you haven't just made a transaction or I'd see a locked balance but there could still be an edge case in the older code which is in production) 
We've made lots of improvements to this system - some of which are waiting to be deployed to production - and however unlikely these issues are in the first place, we take them very seriously as this is obviously not something where we can afford inaccuracies. Unfortunately, reaching the point where the scanning system is as rock solid as banking software appears, with all these underlying systems unique to Monero, it's harder for us than in a typical banking system, and debugging them is considerably harder as well as there are no logins and because the server is highly locked down. 

For that reason, may I ask you to contact support and send your wallet address? That way, fluffypony (Riccardo Spagni) can look up the transactions to see if anything's amiss. 

You can also try waiting up to an hour and seeing if it changes.

**Comment by SergeyAnkarenko** [comment]
Unfortunately, this issue persists. I sent all the required wallet information to Riccardo Spagni. 
I'm eager to see if there are some new updates, related to this issue!

**Comment by paulshapiro** [comment]
I've got better understanding of the issue now. Fixes waiting to be deployed should solve it.
