### ISSUE TITLE
Is API open to be used for other clients?

### ISSUE THREAD

**Issue by p0o** [mymonero/mymonero-app-js#211]
I noticed `api.mymonero.com` provides very fast transaction functions with the tradeoff of giving away the view_key, which is great for some specific lite clients. Is this API open to be used for other clients and if yes, is there any plans for documenting it for developers?

**Comment by paulshapiro** [comment]
Hi, Yes and yes.. we have some other partners interested in and moving forward with integrating github.com/mymonero/mmymonero-core-js to their apps to offer Monero. They will connect to a deployment of our server. One alternative would be deploying your own server, and for this purpose we're releasing a version of our server open source which you can run at home - in the next couple weeks. 

I _may_ migrate the three endpoint calls which are used by the mymonero-core-js lib from `HostedMoneroAPIClient` to the actual lib itself and pass in dependencies such as the parameters like server URL (which can be overridden by settings) so that you don't have to pass that api client dependency.

Going to close this despite your question about documentation as it's more a support or partnership question than an issue with the codebase. Please feel free to open another issue requesting documentation. If you'd like to contribute documentation (perhaps at the mymonero-core-js repo) then that will be very welcome.
