### ISSUE TITLE
Does sending to subaddresses work correctly?

### ISSUE THREAD

**Issue by moneroexamples** [mymonero/mymonero-app-js#237]
I've been testing `mymonero-app-js` on stagenet, and it seems that sending to subaddresses does not work correctly. What I mean is, I can sent to a subaddress, but the funds never arrive to destination. It seems as txs are incorrectly constructed when sending to sub-addresses.

Don't know if this is specific to stagenet only.

**Comment by paulshapiro** [comment]
Hm strange.. I've successfully tested sending to subaddrs in the past. Now we're hooking straight into Monero's cryptonote_tx_utils. Not sure why it would fail. Will look at this asap.

**Comment by moneroexamples** [comment]
It maybe be only stagenet (havent testested mainnet nor testnet). I don't know how exactly it works, its a bit confusing. In here: mymonero_core_js/monero_utils/monero_config.js there are only settings for mainnet. But then you still can use stagenet accounts, by setting nettype to stagnet as show here: https://github.com/mymonero/mymonero-core-js#cryptonote_utilsnettype

Its very confusing which settings are being used.

**Comment by paulshapiro** [comment]
Ah, good point. I'm removing addressPrefix, integratedAddressPrefix, subaddressPrefix from monero_config.js. The nettype arg is specific to each function call.

**Comment by moneroexamples** [comment]
Ok, so settings in `mymonero_core_js/monero_utils/monero_config.js` are can be ignored?

**Comment by paulshapiro** [comment]
Yeah nowadays those are only used for formatting money amounts and determining tx confirmation status.

**Comment by paulshapiro** [comment]
@moneroexamples You were right: https://github.com/mymonero/mymonero-core-cpp/commit/617659c70794dfc8580cb0e5f41f93c4a99bedfc

This fix has now also been rolled out to mymonero-core-js.

Sending to subaddrs was never possible on mymonero.com (even with bulletproofs enabled as we held off updating the rest of the core integrations like decode_addr) – so this issue only affects users who sent to subaddresses using MyMonero desktop and iOS versions 1.1.0 or 1.1.1. 

Note that funds sent to subaddresses in these versions are not lost and are recoverable. Because of the nature of the bug, cryptonote_tx_utils merely didn't update the tx pub key; however, the tx pub key for such txs can still be generated (possibly without even having the tx sec key), though the tx sec keys for txs in MM versions 1.1.0 and 1.1.1 were saved to disk on the senders apps. 

To recover the funds, recipients of these transactions will have to use a new function on the Monero wallet (something like "manual tx pub key") that would take as inputs a tx hash and a key, then the wallet would use that when scanning that tx and when making a future tx based on that transaction's output(s).

MyMonero users should update their apps to the newest version (1.1.2) once it comes out of release-candidate mode shortly. A new iOS build will also be available shortly.

Thanks for bringing this to my attention.

**Comment by moneroexamples** [comment]
Thanks for explanation and fix.

I will test it soon and see how it works now.

**Comment by moneroexamples** [comment]
Follow up. Its seems to be working now. thx again.
