### ISSUE TITLE
 Browser build does not start

### ISSUE THREAD

**Issue by Sqorx** [mymonero/mymonero-app-js#305]
If i open the index.html File, I only get an Load circuit.
.

**Comment by devinpearson** [comment]
@Sqorx we have moved the web wallet out into its own repo. it has an updated readme with more details as to how to run it there. you will need to run a simple python HTTP server in order to serve the site.

https://github.com/mymonero/mymonero-web-js.

If you still having issues after running the HTTP server I can assist you further.
