### ISSUE TITLE
i have 0.096xmr,but can't spend 0.06

### ISSUE THREAD

**Issue by Cliff012** [mymonero/mymonero-app-js#353]
it told spendable balance too low,have 0.0098 …… xmr,need 0.06………xmr ,how that happened

**Comment by devinpearson** [comment]
This is due to the Monero Protocol. Monero requires the inputs for its transactions to be confirmed in the wallet before sending them in a new transaction. So if there is a single input of say 1XMR and you send 0.5XMR on. you won't be able to spend the leftover 0.5XMR till the change is returned. in this case, your balance would be 0.5XMr but your spendable balance would be 0XMR
