### ISSUE TITLE
Can't send funds

### ISSUE THREAD

**Issue by psmoros** [mymonero/mymonero-app-js#501]
<img width="461" alt="Screenshot 2022-08-17 at 23 41 40" src="https://user-images.githubusercontent.com/17127410/185239093-80d514e5-d021-4d9d-a27a-7d0f2d75706d.png">

When I try to send funds, I see the above error message

### Versions

- mymonero: 1.3.0
- Operating system: macOS Monterrey

**Comment by ferdaaC** [comment]
@psmoros SAME. anyone know a fix I dowloaded the new mac zip. a 2nd application opened. I took the seeds from 2 addresses from the first app and opened them in the 2nd app. tried sending between the two and got the same issue.

couldnt b worse timing. I also sent ~1.5 xmr to a MM address this morning and those funds are not there.

**Comment by stanec** [comment]
Same here. Linux (Fedora 36), tried in two versions of MyMonero (1.3.0 and 1.2.4) and the result is every time the same (as shown in the screenshot above). I temporarily switched to other Monero wallet and it works fine there (just stating it so as to show it's not network problem)

**Comment by ferdaaC** [comment]
@stanec So like I said I dowloaded the my monero wallet mac zip. it didnt replace/update the existing wallet app nut did not work on the new one.

When u used a completely different wallet didyou sweep your keys to the MM addressest that were not working in and it worked? Or are you saying you used a different app, created a new address on said wallet app and only then it worked?

**Comment by stanec** [comment]
@ferdaaC: Yeah, I had to use different monero wallet (different app) as MyMonero has started showing me this bug. I used Monerujo mobile wallet app and I restored wallet from my 25 word seed (I didn't create new wallet) and I was able to send Moneros from it successfully (from the same wallet I wasn't able to send moneros from MyMonero app, I was able to send moneros from Monerujo wallet).

**Comment by ferdaaC** [comment]
@stanec  Cool thanks brotha. in the process of trying to sync my old cake wallet I stopped using last year cause its so fucking slow. Ima give monerujo a go. If theres one plus that comes out of this pain in the ass, I'd be willing to bet money a solid amount of people dusting off their old 2012 mac minis as we speak setting up full node.. I know I am.. not a mac mini but same principal.

Thanks again,

Stay safe

**Comment by AslanPonies** [comment]
Hi @psmoros @ferdaaC @stanec, 

MyMonero PSA

We are currently working on the latest Monero hardfork patch. 

The good news is that wallets are now scanning to their current block height where you are able to view your XMR. We are working on the decoy selection issue which relates to send transactions not confirming. We will update you on when the spending function will be enabled.

**Comment by LivBoss** [comment]
Official PSA from MyMonero:

We are very happy to announce that MyMonero is fully operational again.

We have successfully upgraded our software to Fluorine Fermi to fall in line with the Monero hard fork.

This patch applies to our web-wallet, MacOS and Linux platforms, as well as the Android and iOS mobile apps.

Users will need to update to the latest software in order to use the wallet.
We have found that on some devices, it may be necessary to uninstall and reinstall MyMonero to get the latest software downloaded and operational.

Once you have the latest version of MyMonero installed, you can operate your wallet without issues.
View your XMR balances and transactions, and you can send funds too.

An important note to our Windows users:
We have successfully completed the hard fork upgrades on the Windows software and although we are very eager to release it, we are awaiting an SSL certificate that will allow us to release this software publicly.
This is a priority for us and we will release the latest software for our Windows users as soon as we can.

We will announce once our Windows platforms are available again.

**Comment by karlbuys** [comment]
All platforms are supported again
