### ISSUE TITLE
Problems with the monero Blockchain in common ? 

### ISSUE THREAD

**Issue by skyerjoe** [mymonero/mymonero-app-js#503]
Hello 

Are there any common issues regarding to the main Monero Blockchain ? 

I had mad some transactions with an wallet exchange provider, but the last one one the monero blockchain hasnet changed the Balance from the Wallet. 

So i decided to use the official Wallet and downloaed the entire Blockchain locally. 
This workaround works but also ur wallet the blockchain sync seems really slow 

best regards

**Comment by AslanPonies** [comment]
Hi @skyerjoe , MyMonero PSA

We are currently working on the latest Monero hardfork patch. 

The good news is that wallets are now scanning to their current block height where you are able to view your XMR. We are working on the decoy selection issue which relates to send transactions not confirming. We will update you on when the spending function will be enabled.

**Comment by LivBoss** [comment]
https://github.com/mymonero/mymonero-app-js/issues/515#issue-1354329226

**Comment by LivBoss** [comment]
@skyerjoe

Official PSA from MyMonero:

We are very happy to announce that MyMonero is fully operational again.

We have successfully upgraded our software to Fluorine Fermi to fall in line with the Monero hard fork.

This patch applies to our web-wallet, MacOS and Linux platforms, as well as the Android and iOS mobile apps.

Users will need to update to the latest software in order to use the wallet.
We have found that on some devices, it may be necessary to uninstall and reinstall MyMonero to get the latest software downloaded and operational.

Once you have the latest version of MyMonero installed, you can operate your wallet without issues.
View your XMR balances and transactions, and you can send funds too.

An important note to our Windows users:
We have successfully completed the hard fork upgrades on the Windows software and although we are very eager to release it, we are awaiting an SSL certificate that will allow us to release this software publicly.
This is a priority for us and we will release the latest software for our Windows users as soon as we can.

We will announce once our Windows platforms are available again.
