### ISSUE TITLE
help！show nothing after password

### ISSUE THREAD

**Issue by sonicacd** [mymonero/mymonero-app-js#536]
I used MyMonero wallet to store my 5 private keys, one of which has a 0 balance. I haven't backed them up, and there are about a few hundred Monero coins in total. I'm using the Android system, and nothing is displayed after I enter my password... So now, I can't do anything with my few hundred coins, please help. I am using a Huawei phone, with the Hongmeng 2.0 system.
screenshot：https://i.postimg.cc/FRbwyfTg/20230323173634.jpg

**Comment by karlbuys** [comment]
Are you on a slow internet connection? Sometimes wallets that have lots of transactions take awhile to retrieve the information from the MyMonero server.

Please try log in, and keep your Android phone awake for quite awhile. Potentially up to five minutes.

Please let me know if this resolves your problem

**Comment by sonicacd** [comment]
thank u very much!
After a long wait of about 9 hours or so, I can indeed see it. But is there any way to speed up the browsing? The browsing speed is very slow in both China and Hong Kong.
even with vpn……

**Comment by karlbuys** [comment]
I'm really glad to hear you came right 😃 

Making changes to how long the speed of wallets is something we are considering improving

What I suggest you do is to make new wallets and write down their mnemonic seeds

For now, you can get around this if you sweep your existing wallets to new wallets. Because the new wallets haven't been used yet, it will be much faster 

If you have any problems again, please feel free to open a new ticket or re-open this ticket
